insert into faseproducao (descricao) values ('Malteamento');
insert into faseproducao (descricao) values ('Moagem');
insert into faseproducao (descricao) values ('Misturação');
insert into faseproducao (descricao) values ('Fermentação');
insert into faseproducao (descricao) values ('Destilação');
insert into faseproducao (descricao) values ('Envelhecimento');
insert into faseproducao (descricao) values ('Engarrafamento');
insert into faseproducao (descricao) values ('Rotulagem');
insert into faseproducao (descricao) values ('Armazenamento');
