insert into fatura (preco, descricao) values (1568, 'at nulla suspendisse potenti cras in purus');
insert into fatura (preco, descricao) values (1763, 'posuere felis sed lacus morbi sem');
insert into fatura (preco, descricao) values (1846, 'adipiscing elit proin interdum mauris non ligula');
insert into fatura (preco, descricao) values (2316, 'in purus eu magna vulputate luctus cum sociis natoque penatibus');
insert into fatura (preco, descricao) values (2273, 'mauris vulputate elementum nullam varius nulla facilisi cras non');
insert into fatura (preco, descricao) values (2199, 'pede lobortis ligula sit amet eleifend pede libero');
insert into fatura (preco, descricao) values (1752, 'tortor risus dapibus augue vel accumsan');
insert into fatura (preco, descricao) values (2223, 'ut volutpat sapien arcu sed augue aliquam');
insert into fatura (preco, descricao) values (2107, 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar');
insert into fatura (preco, descricao) values (1902, 'viverra dapibus nulla suscipit ligula in lacus curabitur at');
insert into fatura (preco, descricao) values (2284, 'amet eros suspendisse accumsan tortor quis');
insert into fatura (preco, descricao) values (2438, 'sagittis dui vel nisl duis ac nibh fusce lacus purus');
insert into fatura (preco, descricao) values (2407, 'sed vel enim sit amet nunc');
insert into fatura (preco, descricao) values (2110, 'platea dictumst maecenas ut massa quis');
insert into fatura (preco, descricao) values (2131, 'turpis adipiscing lorem vitae mattis nibh ligula nec sem');
insert into fatura (preco, descricao) values (1571, 'primis in faucibus orci luctus et ultrices posuere cubilia');
insert into fatura (preco, descricao) values (2489, 'est phasellus sit amet erat nulla tempus vivamus in');
insert into fatura (preco, descricao) values (1992, 'hendrerit at vulputate vitae nisl aenean');
insert into fatura (preco, descricao) values (1610, 'donec ut mauris eget massa tempor convallis');
insert into fatura (preco, descricao) values (2250, 'donec ut dolor morbi vel lectus in');
insert into fatura (preco, descricao) values (1533, 'platea dictumst maecenas ut massa quis augue');
insert into fatura (preco, descricao) values (1826, 'ligula suspendisse ornare consequat lectus in est risus auctor sed');
insert into fatura (preco, descricao) values (2341, 'commodo vulputate justo in blandit ultrices enim lorem');
insert into fatura (preco, descricao) values (1701, 'urna ut tellus nulla ut erat id mauris');
insert into fatura (preco, descricao) values (1642, 'sapien urna pretium nisl ut volutpat sapien arcu');
insert into fatura (preco, descricao) values (1602, 'donec diam neque vestibulum eget vulputate ut ultrices vel');
insert into fatura (preco, descricao) values (2059, 'proin interdum mauris non ligula');
insert into fatura (preco, descricao) values (1819, 'nunc proin at turpis a pede posuere nonummy');
insert into fatura (preco, descricao) values (2327, 'aenean sit amet justo morbi ut odio');
insert into fatura (preco, descricao) values (2412, 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat');
insert into fatura (preco, descricao) values (2272, 'posuere cubilia curae nulla dapibus dolor');
insert into fatura (preco, descricao) values (2449, 'luctus ultricies eu nibh quisque id');
insert into fatura (preco, descricao) values (1986, 'vestibulum sit amet cursus id turpis integer aliquet massa');
insert into fatura (preco, descricao) values (1523, 'mi nulla ac enim in tempor turpis nec euismod scelerisque');
insert into fatura (preco, descricao) values (1993, 'libero quis orci nullam molestie nibh in lectus pellentesque at');
insert into fatura (preco, descricao) values (2053, 'pellentesque viverra pede ac diam cras');
insert into fatura (preco, descricao) values (1763, 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin');
insert into fatura (preco, descricao) values (1782, 'mi in porttitor pede justo eu massa donec dapibus duis');
insert into fatura (preco, descricao) values (1766, 'rutrum at lorem integer tincidunt ante');
insert into fatura (preco, descricao) values (1699, 'vel dapibus at diam nam');
insert into fatura (preco, descricao) values (1667, 'in consequat ut nulla sed accumsan');
insert into fatura (preco, descricao) values (1556, 'lorem vitae mattis nibh ligula nec sem duis aliquam');
insert into fatura (preco, descricao) values (2479, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus');
insert into fatura (preco, descricao) values (1600, 'convallis nulla neque libero convallis eget');
insert into fatura (preco, descricao) values (1508, 'hendrerit at vulputate vitae nisl');
insert into fatura (preco, descricao) values (2153, 'pellentesque ultrices mattis odio donec vitae nisi');
insert into fatura (preco, descricao) values (1619, 'praesent blandit lacinia erat vestibulum sed');
insert into fatura (preco, descricao) values (2282, 'vestibulum proin eu mi nulla ac');
insert into fatura (preco, descricao) values (2441, 'justo in blandit ultrices enim lorem ipsum dolor sit amet');
insert into fatura (preco, descricao) values (2249, 'quam suspendisse potenti nullam porttitor lacus at turpis');
